Syntax 4

SectionUseCase."HiFi" {
    Comment "Default HiFi"
    File "/ucm2/Elgato Wave 3/HiFi.conf"
}

SectionDevice."Headphones" {
    Comment "Headphones"
    Value {
        PlaybackChannels 2
        PlaybackPCM "hw:${CardId},0"
        PlaybackMixerElem "PCM"
    }
}

SectionDevice."Microphone" {
    Comment "Microphone"
    Value {
        CaptureChannels 1
        CapturePCM "hw:${CardId},0"
        CaptureMixerElem "Mic"
    }
}
