# ALSA UCM HiFi profile for Elgato Wave:3

SectionVerb."HiFi" {
    EnableSequence [
        cdev "hw:${CardId}"
    ]
    Value {
        TQ "HiFi"
    }
}

SectionDevice."Headphones" {
    Comment "Headphones"
    ConflictingDevice []
    EnableSequence [
        cset "name='PCM Playback Switch' on"
    ]
    DisableSequence [
        cset "name='PCM Playback Switch' off"
    ]
    Value {
        PlaybackChannels 2
        PlaybackPCM "hw:${CardId},0"
        PlaybackMixerElem "PCM"
        PlaybackMasterElem "PCM"
    }
}

SectionDevice."Microphone" {
    Comment "Microphone"
    ConflictingDevice []
    EnableSequence [
        cset "name='Mic Capture Switch' on"
    ]
    DisableSequence [
        cset "name='Mic Capture Switch' off"
    ]
    Value {
        CaptureChannels 1
        CapturePCM "hw:${CardId},0"
        CaptureMixerElem "Mic"
        CaptureMasterElem "Mic"
    }
}
